lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
- jekyll-remote-theme
title: DOLAP
description: International Workshop on Design, Optimization, Languages and Analytical Processing of Big Data
fixed_navbar: top