lsi: false
safe: true
source: src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
- jekyll-remote-theme
title: DOLAP
description: International Workshop on Design, Optimization, Languages and Analytical Processing of Big Data
google_analytics: G-WLT2T3GPYF
fixed_navbar: top
